mssql:
  datasource:
    jdbc-url: ${TT_DATASOURCE_URL}
    driver-class-name: ${TT_DATASOURCE_DRIVER}
    username: ${TT_DATASOURCE_USERNAME}
    password: ${TT_DATASOURCE_PASSWORD}

spring:
  jpa:
    show-sql: true
  config:
    import: env.properties

springdoc:
  swagger-ui:
    enabled: true

jwt:
  secret: ${TT_JWT_SECRET}
  expiration: 3600 #Token expiration in minutes